set(PERCEPTSHIFT_PRODUCT_NAME "PerceptShift")
set(PERCEPTSHIFT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(PERCEPTSHIFT_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(PERCEPTSHIFT_VERSION_PATCH ${PROJECT_VERSION_PATCH})

find_package(Git QUIET)
set(PERCEPTSHIFT_GIT_COMMIT "unknown")
if(GIT_FOUND AND EXISTS "${CMAKE_SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    OUTPUT_VARIABLE PERCEPTSHIFT_GIT_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
  )
  if(PERCEPTSHIFT_GIT_COMMIT STREQUAL "")
    set(PERCEPTSHIFT_GIT_COMMIT "unknown")
  endif()
endif()

configure_file(
  "${CMAKE_SOURCE_DIR}/cpp/include/perceptshift/version.hpp.in"
  "${CMAKE_BINARY_DIR}/generated/perceptshift/version.hpp"
  @ONLY
)
